[
  {
    id: 1,
    title: "Apple iPhone 15 Pro",
    description: "Latest iPhone with A17 Pro chip and titanium frame.",
    country: "USA",
    price: "$999",
    category: "Smartphones",
    ImageUrl: "https://example.com/iphone15pro.jpg",
  },
  {
    id: 2,
    title: "Samsung Galaxy S24 Ultra",
    description: "Flagship Android phone with S Pen and 200MP camera.",
    country: "South Korea",
    price: "$1199",
    category: "Smartphones",
    ImageUrl: "https://example.com/galaxys24ultra.jpg",
  },
  {
    id: 3,
    title: "MacBook Air M3",
    description: "Lightweight laptop with M3 chip and 18-hour battery life.",
    country: "USA",
    price: "$1299",
    category: "Laptops",
    ImageUrl: "https://example.com/macbookairm3.jpg",
  },
  {
    id: 4,
    title: "Dell XPS 15",
    description: "Premium Windows laptop with OLED display and Intel Core i9.",
    country: "USA",
    price: "$1899",
    category: "Laptops",
    ImageUrl: "https://example.com/dellxps15.jpg",
  },
  {
    id: 5,
    title: "Nike Air Jordan 1",
    description: "Classic sneakers with high-top design and leather upper.",
    country: "USA",
    price: "$180",
    category: "Fashion",
    ImageUrl: "https://example.com/airjordan1.jpg",
  },
  {
    id: 6,
    title: "Adidas Ultraboost 23",
    description: "Running shoes with responsive Boost cushioning.",
    country: "Germany",
    price: "$160",
    category: "Fashion",
    ImageUrl: "https://example.com/ultraboost23.jpg",
  },
  {
    id: 7,
    title: "Sony WH-1000XM5",
    description: "Industry-leading noise-canceling headphones.",
    country: "Japan",
    price: "$399",
    category: "Audio",
    ImageUrl: "https://example.com/sonywh1000xm5.jpg",
  },
  {
    id: 8,
    title: "Bose QuietComfort Ultra",
    description: "Comfortable over-ear headphones with immersive sound.",
    country: "USA",
    price: "$429",
    category: "Audio",
    ImageUrl: "https://example.com/boseqc.jpg",
  },
  {
    id: 9,
    title: "Apple Watch Ultra 2",
    description: "Rugged smartwatch designed for extreme sports.",
    country: "USA",
    price: "$799",
    category: "Wearables",
    ImageUrl: "https://example.com/applewatchultra2.jpg",
  },
  {
    id: 10,
    title: "Samsung Galaxy Watch 6 Classic",
    description: "Premium smartwatch with rotating bezel and health tracking.",
    country: "South Korea",
    price: "$449",
    category: "Wearables",
    ImageUrl: "https://example.com/galaxywatch6classic.jpg",
  },
];
